language: node_js
node_js:
  - "4.0"
  - "iojs"
  - "0.12"
  - "0.10"
notifications:
  email:
    - shuanwang@gmail.com
env:
  - CXX=g++-4.8
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8
